export const symbols = [
  // 📈 Indices
  { type: "index", symbol: "NSE:NIFTY50" },
  { type: "index", symbol: "NSE:BANKNIFTY" },
  { type: "index", symbol: "NSE:NIFTYIT" },
  { type: "index", symbol: "NSE:NIFTYFIN" },
  { type: "index", symbol: "NSE:NIFTYAUTO" },

  // 🏦 Major Stocks
  { type: "stock", symbol: "RELIANCE" },
  { type: "stock", symbol: "TCS" },
  { type: "stock", symbol: "INFY" },
  { type: "stock", symbol: "HDFCBANK" },
  { type: "stock", symbol: "ICICIBANK" },
  { type: "stock", symbol: "LT" },
  { type: "stock", symbol: "SBIN" },
  { type: "stock", symbol: "ITC" },
  { type: "stock", symbol: "HINDUNILVR" },
  { type: "stock", symbol: "MARUTI" },
  { type: "stock", symbol: "AXISBANK" },
  { type: "stock", symbol: "KOTAKBANK" },
  { type: "stock", symbol: "BAJFINANCE" },
  { type: "stock", symbol: "BHARTIARTL" },
  { type: "stock", symbol: "SUNPHARMA" },
  { type: "stock", symbol: "TATAMOTORS" },
  { type: "stock", symbol: "TATASTEEL" },
  { type: "stock", symbol: "HCLTECH" },
  { type: "stock", symbol: "WIPRO" },
  { type: "stock", symbol: "ADANIENT" },
  { type: "stock", symbol: "POWERGRID" },
  { type: "stock", symbol: "ULTRACEMCO" },
  { type: "stock", symbol: "ONGC" },
  { type: "stock", symbol: "COALINDIA" },
  { type: "stock", symbol: "HDFCLIFE" },
   { type: "stock", symbol: "TESLA" },
  { type: "stock", symbol: "APPLE" },
  { type: "stock", symbol: "NVIDIA" },

  // 💎 Cryptos
  { type: "crypto", symbol: "BINANCE:BTCUSDT" },
  { type: "crypto", symbol: "BINANCE:ETHUSDT" },
  { type: "crypto", symbol: "BINANCE:SOLUSDT" },
  { type: "crypto", symbol: "BINANCE:XRPUSDT" },
  { type: "crypto", symbol: "BINANCE:ADAUSDT" },
  { type: "crypto", symbol: "BINANCE:DOGEUSDT" },
  { type: "crypto", symbol: "BINANCE:MATICUSDT" },
  { type: "crypto", symbol: "BINANCE:AVAXUSDT" },
  { type: "crypto", symbol: "BINANCE:DOTUSDT" },
  { type: "crypto", symbol: "BINANCE:LTCUSDT" },
];
